from classes import *

UNKNOWN_STACK_SIZE = -1

__science_faucet = False

__ = [

    Thing("Meta_Target_Science", UNKNOWN_STACK_SIZE, should_faucet = False),
    Thing("Meta_Target_Mall", UNKNOWN_STACK_SIZE, should_faucet = False),


    Thing("Automation Science Pack", 200, should_faucet = __science_faucet),
    Thing("Py1 Science Pack", 200, should_faucet = __science_faucet),
    Thing("Logistic Science Pack", 200, should_faucet = __science_faucet),
    Thing("Py2 Science Pack", 200, should_faucet = __science_faucet),
    Thing("Chemical Science Pack", 200, should_faucet = __science_faucet),
    Thing("Vatbrain Cartridge Mk1", UNKNOWN_STACK_SIZE, should_faucet=__science_faucet),

    Thing("Niobium-Aluminium-Titanium Special Alloy", UNKNOWN_STACK_SIZE),
    Thing("MW", 1),
    Thing("Native Flora", 50),
    Thing("Log", 100),
    Thing("Ash", 1000),
    Thing("Stone Brick", 100),
    Thing("Iron Plate", 100),
    Thing("Copper Plate", 100),

    Thing("Urea", 100),
    Thing("Glass", 100),
    Thing("Crushed Quartz", UNKNOWN_STACK_SIZE),
    Thing("Methane", UNKNOWN_STACK_SIZE),
    Thing("Sulfur", UNKNOWN_STACK_SIZE),
    Thing("Kevlar", UNKNOWN_STACK_SIZE),
    Thing("Photophore", UNKNOWN_STACK_SIZE),
    Thing("Iron-Niobium Alloy", UNKNOWN_STACK_SIZE),
    Thing("Silver plate", UNKNOWN_STACK_SIZE),
    Thing("Niobium Complex", UNKNOWN_STACK_SIZE),
    Thing("Sulfuric Acid", UNKNOWN_STACK_SIZE),
    Thing("Aramid Fiber", UNKNOWN_STACK_SIZE),
    Thing("Benzene", UNKNOWN_STACK_SIZE),
    Thing("Hot Air", UNKNOWN_STACK_SIZE),
    Thing("Organic Solvent", UNKNOWN_STACK_SIZE),
    Thing("Optical Fiber", UNKNOWN_STACK_SIZE),
    Thing("Steel Plate", UNKNOWN_STACK_SIZE),

    Thing("Acid Gas", UNKNOWN_STACK_SIZE),
    Thing("Lightly N-Doped Silicon", UNKNOWN_STACK_SIZE),
    Thing("Tuuphra", UNKNOWN_STACK_SIZE),
    Thing("Zipir Egg", UNKNOWN_STACK_SIZE),
    Thing("Petroleum Gas", UNKNOWN_STACK_SIZE),
    Thing("Titanium Plate", UNKNOWN_STACK_SIZE),
    Thing("Anthraquine", UNKNOWN_STACK_SIZE),
    Thing("Green Sic", UNKNOWN_STACK_SIZE),
    Thing("Bones", UNKNOWN_STACK_SIZE),
    Thing("Btx", UNKNOWN_STACK_SIZE),
    Thing("Antimony Oxide", UNKNOWN_STACK_SIZE),
    Thing("Aromatics", UNKNOWN_STACK_SIZE),
    Thing("Naphta", UNKNOWN_STACK_SIZE),
    Thing("Aluminium Pulp", UNKNOWN_STACK_SIZE),
    Thing("Uranium Ore", UNKNOWN_STACK_SIZE),
    Thing("Acetylene", UNKNOWN_STACK_SIZE),
    Thing("Silicon Wafer", UNKNOWN_STACK_SIZE),
    Thing("Acetone", UNKNOWN_STACK_SIZE),
    Thing("Arqad Venom", UNKNOWN_STACK_SIZE),
    Thing("Cermet", UNKNOWN_STACK_SIZE),
    Thing("Coal", UNKNOWN_STACK_SIZE),
    Thing("Heavily N-Doped Silicon", UNKNOWN_STACK_SIZE),
    Thing("Methanol", UNKNOWN_STACK_SIZE),
    Thing("Crude Oil", UNKNOWN_STACK_SIZE),
    Thing("Iron Plates", UNKNOWN_STACK_SIZE),
    Thing("Fish", UNKNOWN_STACK_SIZE),
    Thing("Titanium Plates", UNKNOWN_STACK_SIZE),
    Thing("Antimony Pulp 2", UNKNOWN_STACK_SIZE),
    Thing("Molten Chromium", UNKNOWN_STACK_SIZE),
    Thing("Skin", UNKNOWN_STACK_SIZE),
    Thing("Rare-Earth Oxides", UNKNOWN_STACK_SIZE),
    Thing("Natural Gas", UNKNOWN_STACK_SIZE),
    Thing("Oleochemicals", UNKNOWN_STACK_SIZE),
    Thing("Nylon", UNKNOWN_STACK_SIZE),
    Thing("Formic Acid", UNKNOWN_STACK_SIZE),
    Thing("Ferrite", UNKNOWN_STACK_SIZE),
    Thing("Melamine Resin", UNKNOWN_STACK_SIZE),
    Thing("Biomass", UNKNOWN_STACK_SIZE),
    Thing("Coal Dust", UNKNOWN_STACK_SIZE),
    Thing("Urea (No!", UNKNOWN_STACK_SIZE),
    Thing("Phosphine Gas", UNKNOWN_STACK_SIZE),
    Thing("Heavy N-Doped Silicon", UNKNOWN_STACK_SIZE),
    Thing("Naphthalene Oil", UNKNOWN_STACK_SIZE),
    Thing("Aluminium Plate", UNKNOWN_STACK_SIZE),
    Thing("Lead-Antimony Alloy", UNKNOWN_STACK_SIZE),
    Thing("Quartz", UNKNOWN_STACK_SIZE),
    Thing("Antimony Grade 4", UNKNOWN_STACK_SIZE),
    Thing("Nickel Plate", UNKNOWN_STACK_SIZE),
    Thing("Intermetallics", UNKNOWN_STACK_SIZE),
    Thing("Chromium", UNKNOWN_STACK_SIZE),
    Thing("Cobalt Extract", UNKNOWN_STACK_SIZE),
    Thing("Rayon", UNKNOWN_STACK_SIZE),
    Thing("Red Hot Coke", UNKNOWN_STACK_SIZE),
    Thing("Phenol", UNKNOWN_STACK_SIZE),
    Thing("Molybdenum Ore", UNKNOWN_STACK_SIZE),
    Thing("Moss", UNKNOWN_STACK_SIZE),
    Thing("Ethylene", UNKNOWN_STACK_SIZE),
    Thing("Silicon", UNKNOWN_STACK_SIZE),
    Thing("Condensates", UNKNOWN_STACK_SIZE),
    Thing("Korlex Milk", UNKNOWN_STACK_SIZE),
    Thing("Etching Solution", UNKNOWN_STACK_SIZE),
    Thing("Hydrofluoric Acid", UNKNOWN_STACK_SIZE),
    Thing("Cottongut", UNKNOWN_STACK_SIZE),
    Thing("Lard", UNKNOWN_STACK_SIZE),
    Thing("Boric Acid", UNKNOWN_STACK_SIZE),
    Thing("Stainless Steel", UNKNOWN_STACK_SIZE),
    Thing("Organic Acid Anhydride", UNKNOWN_STACK_SIZE),
    Thing("Limestone", UNKNOWN_STACK_SIZE),
    Thing("Agar", UNKNOWN_STACK_SIZE),
    Thing("Coke", UNKNOWN_STACK_SIZE),
    Thing("Syngas", UNKNOWN_STACK_SIZE),
    Thing("Gravel", UNKNOWN_STACK_SIZE),
    Thing("Salt", UNKNOWN_STACK_SIZE),
    Thing("Fiberboard", UNKNOWN_STACK_SIZE),
    Thing("Creosote", UNKNOWN_STACK_SIZE),
    Thing("Tall Oil", UNKNOWN_STACK_SIZE),
    Thing("Battery", UNKNOWN_STACK_SIZE),
    Thing("Stone Bricks", UNKNOWN_STACK_SIZE),
    Thing("Shale Oil", UNKNOWN_STACK_SIZE),
    Thing("Vatbrain Cartridge Mk2", UNKNOWN_STACK_SIZE),
    Thing("Petri Dish", UNKNOWN_STACK_SIZE),
    Thing("Fertilizer", UNKNOWN_STACK_SIZE),
    Thing("Medium-Power Resistors", UNKNOWN_STACK_SIZE),
    Thing("Nickel Ore", UNKNOWN_STACK_SIZE),
    Thing("Lightly P-Doped Silicon", UNKNOWN_STACK_SIZE),
    Thing("Meat", UNKNOWN_STACK_SIZE),
    Thing("Aluminium", UNKNOWN_STACK_SIZE),
    Thing("Brain", UNKNOWN_STACK_SIZE),
    Thing("Ammonia", UNKNOWN_STACK_SIZE),
    Thing("Raw Fiber", UNKNOWN_STACK_SIZE),
    Thing("Acetic Acid", UNKNOWN_STACK_SIZE),
    Thing("Iron Oxide", UNKNOWN_STACK_SIZE),
    Thing("Phosphorous Pentasulfide", UNKNOWN_STACK_SIZE),
    Thing("Anthraquinone", UNKNOWN_STACK_SIZE),
    Thing("Zinc", UNKNOWN_STACK_SIZE),
    Thing("Iron Ore Dust", UNKNOWN_STACK_SIZE),
    Thing("Copper", UNKNOWN_STACK_SIZE),
    Thing("Fatty Acids", UNKNOWN_STACK_SIZE),
    Thing("Crushed Oil Sands", UNKNOWN_STACK_SIZE),
    Thing("Rare Earth Ore", UNKNOWN_STACK_SIZE),
    Thing("Kicalk", UNKNOWN_STACK_SIZE),
    Thing("Unslimed Iron", UNKNOWN_STACK_SIZE),
    Thing("Laboratory Instrument", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Rubber", UNKNOWN_STACK_SIZE, should_faucet=True),
    Thing("Molten Nickel", UNKNOWN_STACK_SIZE),
    Thing("Anthracene Oil", UNKNOWN_STACK_SIZE),
    Thing("Sand", UNKNOWN_STACK_SIZE),
    Thing("Borax", UNKNOWN_STACK_SIZE),
    Thing("Optical Set", UNKNOWN_STACK_SIZE),
    Thing("Molten Glass", UNKNOWN_STACK_SIZE),
    Thing("Nexelit Plate", UNKNOWN_STACK_SIZE),
    Thing("Lead Plate", UNKNOWN_STACK_SIZE),
    Thing("Copper Ore (?", UNKNOWN_STACK_SIZE),
    Thing("Molybdenum Trioxide", UNKNOWN_STACK_SIZE),
    Thing("Arthropod Blood", UNKNOWN_STACK_SIZE),
    Thing("Self-Assembly Monolayer Material", UNKNOWN_STACK_SIZE),
    Thing("Phosphate Rock", UNKNOWN_STACK_SIZE),
    Thing("Plasmids", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Ulrics", UNKNOWN_STACK_SIZE),
    Thing("Solder", UNKNOWN_STACK_SIZE),
    Thing("Sodium Hydroxide", UNKNOWN_STACK_SIZE),
    Thing("150C Steam", UNKNOWN_STACK_SIZE),
    Thing("Vitreloy", UNKNOWN_STACK_SIZE),
    Thing("Bakelite", UNKNOWN_STACK_SIZE),
    Thing("Tin Plate", UNKNOWN_STACK_SIZE),
    Thing("Chrome Sand", UNKNOWN_STACK_SIZE),
    Thing("Tailings Dust", UNKNOWN_STACK_SIZE),
    Thing("Duralumin", UNKNOWN_STACK_SIZE),
    Thing("Tailings", UNKNOWN_STACK_SIZE),
    Thing("Blood", UNKNOWN_STACK_SIZE),
    Thing("Antimony Pulp 02", UNKNOWN_STACK_SIZE),
    Thing("Molten Aluminium", UNKNOWN_STACK_SIZE),
    Thing("Tci_Todo_Internal", UNKNOWN_STACK_SIZE),
    Thing("Complex Circuit Board", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Mibc", UNKNOWN_STACK_SIZE),
    Thing("Molybdenum Plate", UNKNOWN_STACK_SIZE),
    Thing("Plastic", UNKNOWN_STACK_SIZE),
    Thing("Chitin", UNKNOWN_STACK_SIZE),
    Thing("Logs", UNKNOWN_STACK_SIZE),
    Thing("Kw", UNKNOWN_STACK_SIZE),
    Thing("Ralesias", UNKNOWN_STACK_SIZE),
    Thing("Manure", UNKNOWN_STACK_SIZE),
    Thing("Activated Carbon", UNKNOWN_STACK_SIZE),
    Thing("Geothermal Water", UNKNOWN_STACK_SIZE),
    Thing("Niobium Plate", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Glassware", UNKNOWN_STACK_SIZE),
    Thing("Soil", UNKNOWN_STACK_SIZE),
    Thing("Steel", UNKNOWN_STACK_SIZE),
    Thing("Carbonyl Sulfide", UNKNOWN_STACK_SIZE),
    Thing("Lubricant", UNKNOWN_STACK_SIZE),
    Thing("Copper Ore", UNKNOWN_STACK_SIZE),
    Thing("Tin Grade 1", UNKNOWN_STACK_SIZE),
    Thing("Vrauk Food", UNKNOWN_STACK_SIZE),
    Thing("Bone Meal", UNKNOWN_STACK_SIZE),
    Thing("Aramid", UNKNOWN_STACK_SIZE),
    Thing("Coal Gas", UNKNOWN_STACK_SIZE),
    Thing("Simple Circuit Board", UNKNOWN_STACK_SIZE, False),
    Thing("Filtration Media", UNKNOWN_STACK_SIZE),
    Thing("Ulric", UNKNOWN_STACK_SIZE),
    Thing("Fish Oil", UNKNOWN_STACK_SIZE),
    Thing("Phytoplankton", UNKNOWN_STACK_SIZE),
    Thing("Moondrop", UNKNOWN_STACK_SIZE),
    Thing("Nichrome", UNKNOWN_STACK_SIZE),
    Thing("Aluminium Pulp 1", UNKNOWN_STACK_SIZE),
    Thing("Vrauk", UNKNOWN_STACK_SIZE),
    Thing("Phosphoric Acid", UNKNOWN_STACK_SIZE),
    Thing("Zinc Ore", UNKNOWN_STACK_SIZE),
    Thing("Raw Coal", UNKNOWN_STACK_SIZE),
    Thing("Melamine", UNKNOWN_STACK_SIZE),
    Thing("Sodium Carbonate", UNKNOWN_STACK_SIZE),
    Thing("Gasoline", UNKNOWN_STACK_SIZE),
    Thing("Stone", UNKNOWN_STACK_SIZE),
    Thing("Ethylene Glycol", UNKNOWN_STACK_SIZE),
    Thing("Heavy Oil", UNKNOWN_STACK_SIZE),
    Thing("Zinc Plate", UNKNOWN_STACK_SIZE),
    Thing("Rare-Earth Ore", UNKNOWN_STACK_SIZE),
    Thing("Naphtha", UNKNOWN_STACK_SIZE),
    Thing("Tar", UNKNOWN_STACK_SIZE),
    Thing("Lamp", UNKNOWN_STACK_SIZE),
    Thing("Sand Casting", UNKNOWN_STACK_SIZE),
    Thing("Uranium", UNKNOWN_STACK_SIZE),
    Thing("Iron-Nexelit-Antimony Alloy", UNKNOWN_STACK_SIZE),
    Thing("Molten Copper", UNKNOWN_STACK_SIZE),
    Thing("Navens", UNKNOWN_STACK_SIZE),
    Thing("Slaked Lime", UNKNOWN_STACK_SIZE),
    Thing("Flue Gas", UNKNOWN_STACK_SIZE),
    Thing("Iron Ore", UNKNOWN_STACK_SIZE),
    Thing("Chromite Sand", UNKNOWN_STACK_SIZE),
    Thing("Ceramic", UNKNOWN_STACK_SIZE),
    Thing("Hydrogen Peroxide", UNKNOWN_STACK_SIZE),
    Thing("Drill Head", UNKNOWN_STACK_SIZE),
    Thing("Guts", UNKNOWN_STACK_SIZE),
    Thing("Todo_Internal_Acetone", UNKNOWN_STACK_SIZE),
    Thing("Plutonium-242", UNKNOWN_STACK_SIZE),
    Thing("Plutonium-238", UNKNOWN_STACK_SIZE),
    Thing("Industrial Solvent", UNKNOWN_STACK_SIZE),
    Thing("Uranium-238", UNKNOWN_STACK_SIZE),
    Thing("Plutonium-241", UNKNOWN_STACK_SIZE),
    Thing("Small Parts", UNKNOWN_STACK_SIZE),
    Thing("Ethanol", UNKNOWN_STACK_SIZE),
    Thing("Mechanical Parts Mk1", UNKNOWN_STACK_SIZE),
    Thing("Plutonium-25.4", UNKNOWN_STACK_SIZE),
    Thing("Plutonium-240", UNKNOWN_STACK_SIZE),
    Thing("Advanced Small Parts", UNKNOWN_STACK_SIZE, should_faucet=False),
    
    Thing("Boron Trioxide", UNKNOWN_STACK_SIZE),
    Thing("Todo_Internal_Smallparts", UNKNOWN_STACK_SIZE),
    Thing("Todo_Internal_Labeqchassis", UNKNOWN_STACK_SIZE),
    Thing("Bone", UNKNOWN_STACK_SIZE),
    
    Thing("Molten Lead", UNKNOWN_STACK_SIZE),

    
    Thing("Electrolytic Capacitors", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Microchips", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Tinned Cable", UNKNOWN_STACK_SIZE),
    Thing("Toroidal Inductors", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Green S.I.C.", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Printed Circuit Substrate Mk2", UNKNOWN_STACK_SIZE),
    Thing("Diodes", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Mosfet", UNKNOWN_STACK_SIZE, should_faucet=False),
    Thing("Transistors", UNKNOWN_STACK_SIZE, should_faucet=False),
    
    Thing("Todo_Blood", UNKNOWN_STACK_SIZE),
    Thing("Copper Grade 4", UNKNOWN_STACK_SIZE),
    
    Thing("Cyanic Acid", UNKNOWN_STACK_SIZE),

    
    Thing("Good Alien Sample", UNKNOWN_STACK_SIZE),
    Thing("Casein", UNKNOWN_STACK_SIZE),
    Thing("Solidified Sarcorus", UNKNOWN_STACK_SIZE),
    Thing("Arqad Honey", UNKNOWN_STACK_SIZE),
    Thing("Paragen", UNKNOWN_STACK_SIZE),


    Thing("Propene", UNKNOWN_STACK_SIZE),
    Thing("Low Distillates", UNKNOWN_STACK_SIZE),
    Thing("Hydrogen Chloride", UNKNOWN_STACK_SIZE),
    Thing("Alien Sample", UNKNOWN_STACK_SIZE),
    Thing("Microfiber", UNKNOWN_STACK_SIZE),
    Thing("Tin-Chromium Alloy", UNKNOWN_STACK_SIZE),
    Thing("Incubated Petri Dish", UNKNOWN_STACK_SIZE),
    Thing("Xylenol", UNKNOWN_STACK_SIZE),
    Thing("Titanium Tetrachloride", UNKNOWN_STACK_SIZE),
    Thing("Primers", UNKNOWN_STACK_SIZE),
    Thing("Formamide", UNKNOWN_STACK_SIZE),
    Thing("Lead Dust", UNKNOWN_STACK_SIZE),
    Thing("Fatty Acid", UNKNOWN_STACK_SIZE),
    Thing("Dna Polymerase", UNKNOWN_STACK_SIZE),
    Thing("Meta_Target_Planned", UNKNOWN_STACK_SIZE),
    Thing("Molten Tin", UNKNOWN_STACK_SIZE),
    Thing("Biosample", UNKNOWN_STACK_SIZE),
    Thing("Grease", UNKNOWN_STACK_SIZE),

    
]

T = {}

seen = set()
for _ in __:
    assert _.name.lower() not in seen
    seen.add(_.name.lower())

    T[_.name.upper()] = _
